server:
  port: 8888

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        # 用户服务
        - id: user-service # 路由标识，必须唯一
          uri: lb://user-service # 路由的目标地址，lb为load balance，负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/**,/register,/login,/modifyUserInfo,/current-user,/all-users,/blocked  # 判断请求路径

        # 车票服务
        - id: ticket-service # 路由标识，必须唯一
          uri: lb://ticket-service # 路由的目标地址，lb为load balance，负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/addTicket/**,/delTicket/**,/myTicket,/blocked  # 判断请求路径

        # 车次服务
        - id: train-service # 路由标识，必须唯一
          uri: lb://train-service # 路由的目标地址，lb为load balance，负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/allTrain,/addTrain,/delTrain/**,/modifyTrain/**,/train/return-ticket/**,/train/try-selling-ticket/**,/train/**,/blocked  # 判断请求路径

      globalcors:
        add-to-simple-url-handler-mapping: true # 放行options请求
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            #            allowedOrigins: # 允许哪些网站的跨域请求
            #              - "http://www.scblogs.cn"
            #              - "http://127.0.0.1"
            allowedMethods: # 允许的跨域ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 本次跨域检查的有效期


